# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  body_converter:
    enabled: true # Enable automatic serialization
    validate: true # Enable object validation
    validation_errors_argument: validationErrors
  body_listener:
        enabled: true
        throw_exception_on_unsupported_content_type:  true
        decoders:
            json: fos_rest.decoder.json
  view:
    formats: { json: true, xml: false, rss: false } # Use only JSON
    view_response_listener: true # FOSRESTBundle calls listener to get returned object and serialize it.
    mime_types:
      json: ['application/json', 'application/json;version=1.0']
  serializer:
    serialize_null: true # Show null fields
  format_listener:
      rules:
          - { path: ^/, fallback_format: json, priorities: [ json ] }
          #- { path: ^/, priorities: ['text/html', '*/*'], fallback_format: html, prefer_extension: true }
  param_fetcher_listener: force # Pass parameter by name parameter
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
#    routing_loader: true
#    view:
#        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
